
# Preface {-}

[An archived version of this book is available on Zenodo](https://doi.org/10.5281/zenodo.4850406).

## Content Warning {-}

This book deals with police and corrections violence in frank terminology.
Pictures of chemical weapons being deployed on individuals, including those passively resisting, are included, but no injuries, blood, gore, etc. are shown.
Casualties, including fatalities, are discussed, including an individual being killed by corrections officers.

## Land Acknowledgment {-}

This work's impetus comes from present-day Portland, Oregon, United States of America -- the Indigenous land of the Chinook people, who were colonized and spread across multiple federally recognized tribes in Oregon, Washington and Idaho including Cowlitz, Siletz, Wasco, and Yakima.

Chemical weapons are a common tool among imperialist regimes.
The events cataloged in this book occur at many locations across the present-day United States and internationally, with specific references to Canada, Mexico, and Vietnam, where colonizing forces of (predominately Northwestern) Europe have used forced labor from enslaved Black people to impose significant force on Indigenous cultures and individuals.

No words can fully encompass the place in which each of the stories told in this book occur.
I will work to add important contextual information and acknowledgments, and please remember that each use of a thermal fogger or other brutal police force described here impacted many, many lives.

I ask you to take time to reflect on the countless individuals from communities, tribes, peoples, and cultures around the world that have been fogged with some chemical agent whose names we will never know, whose stories we will never hear.

## Inherent Bias {-}

This book has been produced by collating historical documentation and records, which are inherently biased towards the views of white, male colonizers, as will be plainly evident in the documents.
As such, it is important to recognize that there are almost certainly records that I have not yet found or which have been lost to time.
Even more critical, however, is that many uses of thermal foggers have likely never been recorded at all (even if "legally required"), as will be made clear through the documents that have been recovered.

## Author Position {-}

I, [Dr. Juniper L. Simonis](https://juniperlsimonis.com) (_they/them/theirs_), am a 36-year-old middle-class, white, non-binary, queer, physically and psychologically disabled person. 
I come to the study of the history of chemical weapons use in America via my personal experience being the recipient of law enforcement's chemical weapons and my ensuing scientific research into its impacts on the environment.

I have a PhD in Ecology and Evolutionary Biology from Cornell, where I studied aquatic ecology and biogeochemistry -- disciplines I have put to use to studying the impact of chemical weapons.
Through my ecological research, I have uncovered historical and current information into the impacts of chemical weapons that I was not seeing being represented in the present day broad cultural discourse. 

From this need to share historical information came this book, a way for me to pass along a window into the racist, classist, capitalistic, and colonialistic throughline of the thermal fogger.

I am an abolitionist in multiple senses: I believe that the use of chemical weapons, police, and the carceral system should all be abolished, full-stop.

Through this work, I have discovered an extensive history that makes me feel a deep connection to my protest elders who experienced thermal foggers decades ago.
I hope that my work will bring light to their stories.
We are but the most recent chapter in a long history of United States Law Enforcement using chemical weapons against its own people.

## Financial Statement {-}

All work for this product was conducted by Dr. Juniper L. Simonis via internal time at DAPPER Stats.
No external funding was provided.

## Licenses {-}

This book it created under a [dual license](https://github.com/chemicalweaponsresearch/thermal_fogger/blob/main/LICENSE.md) that recognizes a separation between the software and non-software components.
All underlying documents (photos, etc.) are cited in the [References](#References) and references do not indicate the original licensor endorses this book or its authors.

## Acknowledgments {-}

My deepest heartfelt condolences to the family of Robert Forsythe.
I cannot even begin to imagine the impact Bobby's murder and the subsequent trial and media presence had on you and your community.
I hope that by shining a light on his story now, more people will come to understand just how horrendous the prison system is and fight for its abolition.

The story of Robert Forsythe is almost certainly not unique, and only public knowledge because of the trial against the corrections officers.
I recognize that many others have been killed by thermal foggers, yet we will never know their names.

This booklet is based on a variety of sources past and present, and to the journalists and photographers: thank you for sharing your work with the world. 

I have no idea how many people have been involved in digitizing historical newspapers, as their names are never on anything, but y'all are fantastic and I appreciate you so much.

Sandra Simonis provided significant help with writing alt-text for images.

Twitter users NewNameJeanette and WillHickox notified me of the [Lawrence High School](#Lawrence1970_04_21) protest and use of the thermal fogger, for which I am very thankful.

Christophe Dervieux provided an example of how to render figure alt-text in an appendix: https://cderv.rbind.io/2021/06/29/fig-alt-appendix/.

The cover image is based on @Lewis-Rolland2021a.

## Contribute Information {-} 

If you are aware of incidents where a pepper fogger was used to deploy chemical weapons that we have not included, please reach out [via the Chem Weapons Research Website](https://chemicalweaponsresearch.com/contact/) or submit an [issue](https://github.com/chemicalweaponsresearch/thermal_fogger/issues/new/choose) or [pull request](https://github.com/chemicalweaponsresearch/thermal_fogger/compare) on our [GitHub repository for the book](https://github.com/chemicalweaponsresearch/thermal_fogger).