# The Carceral System {-}

Like many chemical weapons devices, thermal foggers are used in local, state, and federal carceral systems. 
Unfortunately most deployments go undocumented or such documents never see the light of day. 
It seems that the only time we find out about prisoners being fogged is when a serious incident occurs triggering outside investigations and the judicial system.


## McAlester OK, May 20 1974 {-}


In the 1970s, the McAlester ("Big Mac") Oklahoma State Penitentiary was the site of considerable resistance and rioting by inmates [@TheRag1975; @WinterSoldier1975].
A major tool used by the guards in retaliation was tear gas, which they deployed via shot shells, grenades, and pepper foggers [@Allen1974a; @Allen1975a; @Allen1975b; @Coffey1975b].
Given its use here, it is highly likely that the Oklahoma State Penitentiary system used pepper foggers before (and likely after) [@Johnson1974].

The guards regularly isolated the uprising's leaders in the solitary confinement building known as "The Rock", sealed the building, and gassed it so thick it lasted for days [@Allen1974b; @TheRag1975].
During the May 20 gassings in response to riots, Black prisoner Robert Forsythe, a 33-year old serving time for a robbery, happened to be in solitary confinement due to being caught with contraband money and was not associated with the uprising directly, and so inexperienced with the effects of gas [@Johnson1974; @TheRag1975; @Wilson1993].
Although reports are conflicting on details, guards started fogging and gassing prisoners who were, at most, rattling their doors [@Hobbs1974].
The likely reason for the barrage was retaliatory, as it was "unjustified" according to a veteran guard [@Coffey1975a].

During the gassings, a pepper fogger was specifically used in the building and created "fumes of gas [that] were awfully heavy, one of the worst I've ever seen" according to veteran corrections officers' trial testimony [@Allen1975b; @Coffey1975a].
The gassing lasted for four hours despite yells for help, resulting in serious injuries including burned and blistered skin, eyes swollen shut, and breathing difficulties [@Coffey1975b]. 
That intense fogging and lack of medical attention over the next two days were main factors contributing to Forsythe's injuries and death two days later, according to medical experts' testimony [@Allen1974b; @Allen1975a; @Allen1975b].

Although the guards involved were indicted by a grand jury and brought to trial, they ultimately were acquitted of all charges [@UPI1975a; @UPI1975b].



## Raiford FL, July 5 1981 {-}

According to the superintendent, a riot was caused in the Florida State Prison's Union Correctional Institution on July 5th by 22 prisoners who were intoxicated, and the only way to subdue them was to deploy a thermal fogger [@TallahasseeDemocrat1981_07_07].
As a result of two officers being "slightly injured" and three inmates being stabbed, an investigation was launched that caused the event to be picked up in the newspapers [@TallahasseeDemocrat1981_07_07].




## Miami FL, July 17 1974 {-}
 
Dade County Sheriffs used foggers to sweep a field in search of a murder suspect that had eluded K-9 units, helicopters, a plane, and an attempt to flush him out by burning the field [@TampaBayTimes1974_07_18]. 
The suspect was so well dug in that he could withstand significant gassing that surprised a Sheriff's sergeant who participated in the operation [@TampaBayTimes1974_07_18].

