# Border Patrol: A Second Boomeranging {-}

United States Border Patrol (BP) has played an outsized role in policing and corrections within the federal immigration system and abroad both in support of armed services and independently [@Miller2019].
Indeed, BP has provided another boomeranging of the Imperial Tetherball that bridges the Vietnam-era and present-day domestic applications via export to foreign governments for use in controling their own populaces.

### International Trafficking

Within a year and a half of the fogger's arrival to US domestic police agencies, BP agents were engaging foreign governments independent of the military on chemical weapons deployment including using thermal foggers.
During April 25 - May 9 of 1970, Raymond Dee Bond, a Border Patrol agent with decades of experience, sold $15,000 worth of chemical weaponry to the Mexican federal government [@ValleyMorningStar1973_08_04].
Included in the cache were multiple pepper foggers and formulations [@ValleyMorningStar1973_08_04].
Bond was caught and charges with weapons trafficking and acting as a foreign agent without notifying the Secretary of State [@DailyNews1972_10_27].
Although indicted by a federal grand jury, Bond was able to escape prosecution by resigning from his position  [@ValleyMorningStar1973_08_04].

Given the extensive reach of Border Patrol into Central and South America fueled in particular by the 'Drug War' [@Chepesiuk1999], it is reasonable to expect that this was not an isolated event.

### BORTAC {-}

By 2020, the Border Patrol Tactical Unit (BORTAC) had been established to, among other tasks, provide particularly extreme responses to domestic as well as foreign uprisings [@CBP2006; @CBP2014; @CBP2018].
BORTAC is truly a global domestic law enforcement agency, operating in 28 countries (they were willing to publicly disclose as of 2006, @CBP2006), providing a wide range of services [@CBP2014; @Miller2019].
BORTAC's specific genesis was focused on riots in federal immigration detention centers [@CBP2006; @CBP2014], noteworthy given the use of thermal foggers in the United States [carceral system](@CarceralSystem).

BORTAC would be the unit to bring the thermal fogger back to use against domestic civilian protesters during the [Black Lives Matter](#PortlandOR2020_07_29) and [Ablolish ICE](#PortlandORICE2020_2021) protests in Portland Oregon during 2020 and 2021.
Indeed, Border Patrol agents from the El Paso unit specifically were deployed to police protests in El Paso in addition to being sent to Portland and other cities like Albuquerque, New Mexico [@Borunda2020].

