# building website
# based on https://github.com/r-lib/actions/blob/v2-branch/examples/bookdown.yaml

on:
  push:
    branches:
      - main

name: bookdown

jobs:
  bookdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true 

      - uses: r-lib/actions/setup-renv@v2

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Build books and send to rstudio
        run: |
          bookdown::render_book(input = "index.Rmd", output_format = "bookdown::pdf_book")
          bookdown::render_book(input = "index.Rmd", output_format = "bookdown::epub_book")
          bookdown::render_book(input = "index.Rmd", output_format = "bookdown::gitbook")
          bookdown::publish_book(account = "simonis")
        shell: Rscript {0}
